engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
  tslint:
    enabled: true
    channel: beta
    # special config as the engine does not support plugins atm
    config: tslint.codeclimate.json
  duplication:
    enabled: true
    config:
      languages:
        - typescript
        - javascript
ratings:
  paths:
    - "**.js"
    - "**.ts"
    - "**.css"
exclude_paths:
  - "coverage"
  - "node_modules/"
