language: node_js
sudo: true
dist: trusty

node_js:
  - "6.11.0"

notifications:
  email: false

cache:
  directories: node_modules

addons:
apt:
  sources:
    - google-chrome
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g codecov
  - npm install coveralls
  - npm install
  - ng lint
  - ng build --aot --prod
  - ng serve & ng e2e
  - ng test --watch=false --code-coverage
script:
  #- codecov
  - echo "Holaaaaaaaaaaaaa " | ./node_modules/coveralls/bin/coveralls.js
